{% set name = "heligeo" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/heligeo-{{ version }}.tar.gz
  sha256: fce8eac184507927fc39c3a87250da81b9937e420f90d16a8c0d65a51ff4133a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dash ==2.0.0
    - dash-table
    - dash-bootstrap-components
    - dash-core-components
    - dash-html-components
    - numpy
    - pandas
    - plotly
    - python >=3.6
    - requests
    - shapely

test:
  imports:
    - heligeo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/heligeo/
  summary: Python client for requests to heligeo API services
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NandanPattanayak
