{% set name = "heligeo" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/heligeo-{{ version }}.tar.gz
  sha256: 5c88a1a959be225e3fb6bc2060fabb32e14b3d2f9293045881f58a744f35434a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dash
    - numpy
    - pandas
    - plotly
    - python >=3.6
    - requests
    - shapely
    - dash-bootstrap-components

test:
  imports:
    - heligeo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/heligeo/
  summary: Python client for requests to heligeo API services
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NandanPattanayak
