{% set name = "heligeo" %}
{% set version = "1.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/heligeo-{{ version }}.tar.gz
  sha256: 5fe8d9c70d3382260d03b5f9a50a1608f62d1bc22594d1fa975bf5f965f34eec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - plotly
    - python >=3.6
    - requests
    - shapely
    - pandas 

test:
  imports:
    - heligeo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/heligeo/
  summary: Python client for requests to heligeo API services
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NandanPattanayak
